# Generated by Django 6.0 on 2025-12-22 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contractorteam',
            name='supply_chai_package_b8de05_idx',
        ),
        migrations.AlterField(
            model_name='contractorteam',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractorteam',
            name='lead_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractorteam',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='supply_chain.package'),
        ),
        migrations.AlterField(
            model_name='contractorteam',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='supply_chain.project'),
        ),
        migrations.AddIndex(
            model_name='contractorteam',
            index=models.Index(fields=['project', 'status'], name='supply_chai_project_b7a1d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractorteam',
            constraint=models.UniqueConstraint(fields=('project',), name='one_team_per_project'),
        ),
    ]
